version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.2.0
      
    working_directory: ~/rweather
    steps:
      - checkout
      - run:
          name: Download 8.x node
          command: 'curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -'
      - run:
          name: Install Node.JS
          command: 'sudo apt-get install -y nodejs'
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.2.0
    steps:
      - checkout
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master